pipeline{
    agent{
        label 'AGENT-1'
    }
    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    parameters{
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description:'Select Action')
    }
    stages{
        stage('Init and Plan'){
            steps{
                withAWS(region: 'us-east-1', credentials: 'aws-creds'){
                    sh """
                        cd expense-Infra/80-cdn
                        terraform init -reconfigure
                        terraform plan -out=tfplan
                    """
                }
            }
        }
        stage('Apply'){
            input{
                message "Should we continue to ${params.ACTION}"
                ok "yes, we should"
            }
            steps{
                withAWS(region:'us-east-1', credentials: 'aws-creds'){
                    sh """
                        cd expense-Infra/80-cdn
                        if [${params.ACTION} == 'apply']
                        then
                            terraform apply -auto-approve -out=tfplan
                        fi
                    """
                }
            }
        }
        stage('Destroy'){
            when {
                expression { params.ACTION = 'destroy'}
            }
            stage{
                withAWS(region:'us-east-1', credentials: 'aws-creds'){
                    script {
                        def directories = ['80-cdn', '70-ecr', '60-alb', '50-acm', '40-eks', '30-rds', '20-bastion', '10-sg', '00-vpc']
                        for (dir in directories) {
                            echo "Destroying resource in directories: ${dir}"
                            sh """
                                cd ${dir}
                                terraform init -reconfigure
                                terraform destroy -auto-approve || { echo "Failed to destroy resources in ${dir}"; exit 1; }
                                cd ..
                            """
                        }
                    }
                }
            }
        }
    }
    post {
        always{
            echo "This sections runs always"
            deleteDir()
        }
        success{
            echo "This section run when pipeline success"
        }
        failure{
            echo "This section run when pipeline failure"
        }
    }

}