pipeline{
    agent {
        label 'AGENT-1'
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    parameters{
        choice(name: 'ACTION', choices: ['apply', 'detsroy'], description: 'Select Action')
    }
    stages{
        stage('Init and Plan'){
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds'){
                    sh """
                        cd expense-Infra/50-acm
                        terraform init -reconfigure
                        terraform plan -out=tfplan
                    """
                }
            }
        }
        stage('apply or Destroy'){
            input {
                message "SHould we continute to ${params.ACTION}"
                ok "Yes, we should."
            }
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {  // aws-creds credential file should be create in jenkins
                    sh """
                        cd expense-Infra/50-acm
                        if [ ${params.ACTION} == 'apply' ]
                        then
                            terraform apply -auto-approve -out=tfplan
                        elif
                            terraform destroy -auto-approve
                        fi
                    """
                }
            }
        }
    }
    post {
        always{
            echo "This section runs always"
            deleteDir()
        }
        success{
            echo "This section runs when the pipeline success"
            deleteDir()
        }
        failure{
            echo "This section runs when the pipeline failure"
            deleteDir()
        }
    }
}