//UseCase: This file used for to create VPC setup required for application pipeline host as part of Infrastructure Configuration
pipeline {
    agent {
        label 'AGENT-1'
    }
    options {
        timeout(time: 20, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select choice to perform')
    }
    stages{
        stage('Init and Plan') {
            steps{
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd expense-infra/00-vpc
                        terraform init -reconfigure
                        terraform plan -out=tfplan
                    """
                }
            }
        }
        stage('Apply or Destroy') {
            input {
                message "Should we continue to ${params.ACTION}"
                ok "yes, we should."
            }
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd expense-infra/00-vpc
                        if [ ${params.ACTION} == 'apply' ]
                        then
                            terraform apply -auto-approve tfplan
                        elif [ ${ params.ACTION } == 'destroy' ]
                            terraform destroy -auto-approve
                        fi
                    """
                }
            }
        }
        stage('Trigger SG') {
            when {
                expression{ params.ACTION == 'apply' }
            }
            steps {
                build job: '10-sg', parameters: [string(name: 'ACTION', value: 'apply')], wait: false
            }
        }
    }
    post {
        always {
            echo 'This section runs always irrespective of pipeline status'
            deleteDir()
        }
        success {
            echo 'This section runs when the pipeline success'
            deleteDir()
        }
        failure {
            echo ' This section runs when the pipeline failed'
            deleteDir()
        }
    }
}