pipeline{
    agent {
        label 'AGENT-1'
    }
    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansicolor('xterm')
    }
    // environment{
    //     DEBUG = 'true'
    // }
    parameters{
        choice(name: 'ACTION', choices: [ 'apply', 'destroy'], description: 'Select ACTION')
    }
    stages{
        stage('Init & Plan') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd expense-Infra/20-bastion
                        terraform init -reconfigure
                        terraform plan -out=tfplan
                    """
                }
            }
        }
        stage('apply or destroy') {
            input {
                message 'Should we continue to ${params.ACTION}'
                ok 'Yes we should.'
            }
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd expense-Infra/20-bastion
                        if [ ${params.ACTION} == 'apply' ]
                        then
                            terraform apply -auto-approve -out=tfplan
                        elif [ ${params.ACTION} == 'destroy' ]
                        then
                            terraform destroy -auto-approve
                        fi
                    """
                }
            }
        }   
    }
    post {
        always {
            echo 'This section runs always'
            deleteDir()
        }
        success {
            echo 'This section runs when the pipeline success'
            deleteDir()
        }
        failure {
            echo 'This section runs when the pipeline failure'
            deleteDir()
        }
    }
}